format_version: v1.0
type: UniqueComponent
attributes: {id: FreeRTOS}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: FREERTOS_CPU_CLOCK_HZ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '32000000'}
  - type: Boolean
    attributes: {id: FREERTOS_RUN_FREERTOS_SECURE_ONLY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: 'true'}
- type: ElementPosition
  attributes: {x: '17', y: '192', id: FreeRTOS}
