package:
  format-version: "1.0.0"
  name: "core_apps_sam_l10_l11"
  version: "v3.5.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "bsp"
      type: "package"
      version: "v3.17.0"
    - name: "FreeRTOS-Kernel"
      type: "package"
      version: "V11.1.0"
    - name: "core"
      type: "package"
      version: "v3.14.0"
